version: '3.8'

services:

  frontend:
    image: example-frontend
    build: ./1.12/
    ports:
      - 5000:5000

  backend:
    image: example-backend
    build: ./1.13/
    environment: 
      - REDIS_HOST=redis
    ports:
      - 8080:8080

  redis:
    image: redis
    ports:
      - 6379:6379
