version: "3.8"

services:

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  frontend:
    image: example-frontend
    build: ./1.12

  backend:
    image: example-backend
    build: ./1.13
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/temp_db/:/var/lib/postgresql/data:Z

  redis:
    image: redis
    ports:
      - 6379:6379
