version: '3.8'

services:
  frontend:
    image: example-frontend
    build: ./1.12/
    ports:
      - 5000:5000

  backend:
    image: example-backend
    build: ./1.13/
    ports:
      - 8080:8080
